services:
  nuxt-app:
    image: ${PROJECT_NAME}:${TAG:-latest}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./volumes/files/public:/app/${NUXT_FILES_PUBLIC_FOLDER:-files}
      - ./volumes/files/private:/app/${NUXT_FILES_PRIVATE_FOLDER:-files}
    ports:
      - ${SERVER_PORT:-3000}:3000
    networks:
      - shared-network

networks:
  shared-network:
    external: true
    name: shared-network
